name: 'restore-vars'
description: 'replace the build output with the original variables when a step function script is edited.'
author: 'bob egan'
inputs:
  dir:  # id of input
    description: 'directory its watching'
    required: true
    default: '../../../deploy/StepFunctions/*.json'
  from: 
  to:
outputs:
  result: # the string
runs: 
  using: 'node16'
  main: 'index.js'
